# This is a basic workflow to help you get started with Actions

name: Run-PesterTests and create PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run-PesterTests:
    # The type of runner that the job will run on
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            ref: develop

      # Clone the repository
      # - name: Pull PsNetTools
      #   run: | 
      #    git pull
      #    git checkout develop
      #  shell: pwsh

      # Runs a set of commands using the runners shell
      - name: Run Pester Tests on develop
        run: |
          cd PsNetTools
          Import-Module -FullyQualifiedName .\PsNetTools.psd1
          cd ../Tests
          Invoke-Pester -Output Detailed
          Remove-Module PsNetTools
        shell: pwsh

  Create-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: develop
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch_prefix: develop
          base_branch: master
          assignees: tinuwalther
          reviewers: tinuwalther